version: '3.6'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
    ports:
      - 80:80
    depends_on:
      - tesler-doc-node-1
      - tesler-doc-node-2
  tesler-doc-node-1:
    build: ./tesler-doc-app
    image: tesler-doc-app:1.0-SNAPSHOT
    environment:
      DATABASE_DRIVER: 'org.postgresql.Driver'
      DATABASE_URL: 'jdbc:postgresql://pgs:5432/postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,address=8989,suspend=n'
    ports:
      - 8081:8080
      - 8981:8989
    depends_on:
      - pgs
  tesler-doc-node-2:
    build: ./tesler-doc-app
    image: tesler-doc-app:1.0-SNAPSHOT
    environment:
      DATABASE_DRIVER: 'org.postgresql.Driver'
      DATABASE_URL: 'jdbc:postgresql://pgs:5432/postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,address=8989,suspend=n'
    ports:
      - 8082:8080
      - 8982:8989
    depends_on:
      - pgs
  pgs:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - 5432:5432