version: '3.6'

services:
  tesler-doc-node-jacoco:
    build: ./tesler-doc-app
    image: tesler-doc-app:latest
    environment:
      DATABASE_DRIVER: 'org.postgresql.Driver'
      DATABASE_URL: 'jdbc:postgresql://pgs-qa:5432/postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'khKJPOsfiwae'
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,address=8989,suspend=n -javaagent:/jacoco/lib/jacocoagent.jar=address=*,port=36320,destfile=/tmp/jacoco-it.exec,output=tcpserver'
    volumes:
      - jacoco:/jacoco:ro
    expose:
      - 8080
      - 36320
    ports:
      - 8080:8080
      - 8981:8989
      - 36320:36320
    depends_on:
      - pgs-qa
      - jacoco
      - sonarqube
  pgs-qa:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=khKJPOsfiwae
    expose:
      - 5432
    ports:
      - 6431:5432
  jacoco:
    image: ictu/jacoco-agent-docker:0.8.6
    volumes:
      - jacoco:/jacoco:ro
  sonarqube:
    image: sonarqube:8.7.1-community
    expose:
      - 9000
    ports:
      - 9000:9000
    environment:

volumes:
  jacoco: