version: '3.6'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - tesler-doc-node-1
      - tesler-doc-node-2
  tesler-doc-node-1:
    image: openjdk:8
    environment:
      DATABASE_DRIVER: 'org.postgresql.Driver'
      DATABASE_URL: 'jdbc:postgresql://pgs:5432/postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
    ports:
      - 8081:8080
      - 8981:8989
    volumes:
      - type: bind
        source: ./tesler-doc-app/
        target: /tmp/tesler-doc-app/
        read_only: true
    command:  bash -c "cp -avr /tmp/tesler-doc-app/target/ /opt/tesler-doc-app/
      && cd /opt/tesler-doc-app/
      && chmod +x tesler-doc-app-exec.jar
      && java '-agentlib:jdwp=transport=dt_socket,server=y,address=8989,suspend=n' -jar tesler-doc-app-exec.jar"
    depends_on:
      - pgs
  tesler-doc-node-2:
    image: openjdk:8
    environment:
      DATABASE_DRIVER: 'org.postgresql.Driver'
      DATABASE_URL: 'jdbc:postgresql://pgs:5432/postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
    ports:
      - 8082:8080
      - 8982:8989
    volumes:
      - type: bind
        source: ./tesler-doc-app/
        target: /tmp/tesler-doc-app/
        read_only: true
    command: bash -c "cp -avr /tmp/tesler-doc-app/target/ /opt/tesler-doc-app/
      && cd /opt/tesler-doc-app/
      && chmod +x tesler-doc-app-exec.jar
      && java '-agentlib:jdwp=transport=dt_socket,server=y,address=8989,suspend=n' -jar tesler-doc-app-exec.jar"
    depends_on:
      - pgs
  pgs:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - 5432:5432