name: Build

on:
  repository_dispatch:
    types: [ test_doc ]
  pull_request:
    branches:
      - develop

jobs:

  build-front:
    name: Build @tesler-ui/core
    runs-on: ubuntu-latest
    if: github.event.client_payload.front.repository != ''
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.front.repository }}
          ref: ${{ github.event.client_payload.front.branch }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          always-auth: true
      - name: install
        run: yarn install
      - name: pack
        id: pack
        run: |
          ls -la
          echo "#############"
          rm -r src
          ls -la
          front_tgz_name=`yarn pack | sed -n 2p | sed 's/.*tarball to \(.*\)\./\1/' | cut -d'"' -f 2 | sed 's/.*\///'`;
          echo "front package path is: $front_tgz_name";
          echo "##[set-output name=front_package_path;]$front_tgz_name"
      - name: Make front artifact dir
        run: |
          mkdir -p artifacts/front
          mv ${{ steps.pack.outputs.front_package_path }} artifacts/front
      - uses: actions/upload-artifact@v2
        with:
          name: front-artifact
          path: artifacts/front/${{ steps.pack.outputs.front_package_path }}

#      - name: Test
#        run: tar zxvf artifacts/front/${{ steps.pack.outputs.front_package_path }}
    outputs:
      front_package_path: ${{ steps.pack.outputs.front_package_path }}

  build:
    name: Build tesler-doc
    runs-on: ubuntu-latest
    needs: [build-front]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          always-auth: true
      - uses: actions/download-artifact@master
        with:
          name: front-artifact
          path: artifacts/front/${{ needs.build-front.outputs.front_package_path }}
      - name: Set front dependence
        if: needs.build-front.outputs.front_package_path != ''
        run: |
          yarn add file:../artifacts/front/${{ needs.build-front.outputs.front_package_path }} --cwd tesler-doc-ui/
#          cd tesler-doc-ui/
#          npm install ../artifacts/front/${{ needs.build-front.outputs.front_package_path }}
#          cd ..
#          yarn install --cwd tesler-doc-ui/
#      - uses: borales/actions-yarn@v2.0.0
#        if: needs.build-front.outputs.front_package_path != ''
#        with:
#          cmd: add file:../artifacts/front/${{ needs.build-front.outputs.front_package_path }} --cwd tesler-doc-ui/

#          yarn add file:../artifacts/front/${{ needs.build-front.outputs.front_package_path }}

#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: clean install
#        run: mvn clean install -P Dev,UI
