name: Build

on:
  repository_dispatch:
    types: [ test_doc ]
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo ${{ github.event.client_payload.front.repository }}
          echo ${{ github.event.client_payload.front.branch }}
#      - uses: actions/checkout@v2
#
#      - name: clean install
#        run: mvn clean install -P Dev,UI
