name: Build

on:
  repository_dispatch:
    types: [ test_doc ]
  pull_request:
    branches:
      - develop

jobs:
  checkout:
    name: Checkout tesler-doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build-front:
    name: Build @tesler-ui/core
#    needs: checkout
    runs-on: ubuntu-latest
    if: github.event.client_payload.front.repository != ''
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.front.repository }}
          ref: ${{ github.event.client_payload.front.branch }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          always-auth: true
      - name: install
        run: yarn install
      - name: pack
        id: pack
        run: |
          front_tgz_path=`yarn pack | sed -n 2p | sed 's/.*tarball to \(.*\)\./\1/' | cut -d'"' -f 2`;
          echo "front package path is: $front_tgz_path";
          echo "##[set-output name=front_package_path;]$front_tgz_path"
    outputs:
      front_package_path: ${{ steps.pack.outputs.front_package_path }}

  set-front-local-dependence:
    name: Set @tesler-ui/core from localc tgz
    runs-on: ubuntu-latest
    needs: [checkout, build-front]
    steps:
      - name: Change dir
        run: |
          cd tesler-doc-ui/
      - name: Set front dependence
        run: |
          yarn add file:${{ needs.build-front.outputs.front_package_path }}

#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: clean install
#        run: mvn clean install -P Dev,UI
