name: Build

on:
  repository_dispatch:
    types: [ test_doc ]
  pull_request:
    branches:
      - develop

jobs:

#  build-back:
#    name: Build tesler
#    runs-on: ubuntu-latest
#    if: github.event.client_payload.back.repository != ''
#    steps:
#      - name: Back triggered
#        run: |
#          echo "${{ toJSON(github.event.client_payload.back) }}"

  build-front:
    name: Build @tesler-ui/core
    runs-on: ubuntu-latest
    if: github.event.client_payload.front.repository != ''
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.front.repository }}
          ref: ${{ github.event.client_payload.front.branch }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          always-auth: true
      - name: install
        run: yarn install
      - name: pack
        id: pack
        run: |
          front_tgz_name=`yarn pack | sed -n 2p | sed 's/.*tarball to \(.*\)\./\1/' | cut -d'"' -f 2 | sed 's/.*\///'`;
          echo "front package path is: $front_tgz_name";
          echo "##[set-output name=front_package_path;]$front_tgz_name"
      - name: Make front artifact dir
        run: |
          mkdir -p artifacts/front
          mv ${{ steps.pack.outputs.front_package_path }} artifacts/front
      - uses: actions/upload-artifact@v2
        with:
          name: front-artifact
          path: artifacts/front/${{ steps.pack.outputs.front_package_path }}

#      - name: Test
#        run: tar zxvf artifacts/front/${{ steps.pack.outputs.front_package_path }}
    outputs:
      front_package_path: ${{ steps.pack.outputs.front_package_path }}

  build:
    name: Build tesler-doc
    runs-on: ubuntu-latest
    if: always()
    needs: [build-front]
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        if: github.event.client_payload.back.repository != ''
        with:
          repository: ${{ github.event.client_payload.back.repository }}
          ref: ${{ github.event.client_payload.back.branch }}
      - name: Build tesler
        if: github.event.client_payload.back.repository != ''
        run: |
          echo "Build tesler triggered"
          mvn versions:set -DnewVersion=test-test
          mvn --batch-mode clean install
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          always-auth: true
      - uses: actions/download-artifact@master
        if: needs.build-front.outputs.front_package_path != ''
        with:
          name: front-artifact
          path: artifacts/front/ #${{ needs.build-front.outputs.front_package_path }}
      - name: Set front dependency
        if: needs.build-front.outputs.front_package_path != ''
        run: |
          ls -la ./artifacts/front/
          yarn add file:../artifacts/front/${{ needs.build-front.outputs.front_package_path }} --cwd tesler-doc-ui/
      - name: clean install with local tesler
        if: github.event.client_payload.back.repository != ''
        run: mvn clean install -P Dev,UI -D tesler.version=test-test
      - name: clean install
        if: github.event.client_payload.back.repository == ''
        run: mvn clean install -P Dev,UI
#          cd tesler-doc-ui/
#          npm install ../artifacts/front/${{ needs.build-front.outputs.front_package_path }}
#          cd ..
#          yarn install --cwd tesler-doc-ui/
#      - uses: borales/actions-yarn@v2.0.0
#        if: needs.build-front.outputs.front_package_path != ''
#        with:
#          cmd: add file:../artifacts/front/${{ needs.build-front.outputs.front_package_path }} --cwd tesler-doc-ui/

#          yarn add file:../artifacts/front/${{ needs.build-front.outputs.front_package_path }}

#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: clean install
#        run: mvn clean install -P Dev,UI
