name: Build

on:
  repository_dispatch:
    types: [ test_doc ]
  pull_request:
    branches:
      - develop

jobs:
  build-front:
    name: Build @tesler-ui/core
    runs-on: ubuntu-latest
    if: github.event.client_payload.front.repository != ''
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.front.repository }}
          ref: ${{ github.event.client_payload.front.branch }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          always-auth: true
      - name: install
        run: yarn install
      - name: pack
        run: |
          yarn pack
#          front_tgz_path=`yarn pack | cut -d'"' -f 2`;
#          echo "front package path is: $front_tgz_path";

#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: clean install
#        run: mvn clean install -P Dev,UI
